// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SVD
List SVD(arma::mat x);
RcppExport SEXP _GGEE_SVD(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SVD(x));
    return rcpp_result_gen;
END_RCPP
}
// cbind1
NumericMatrix cbind1(NumericVector x, NumericVector y);
RcppExport SEXP _GGEE_cbind1(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cbind1(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cbind2
NumericMatrix cbind2(NumericMatrix a, NumericVector b);
RcppExport SEXP _GGEE_cbind2(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cbind2(a, b));
    return rcpp_result_gen;
END_RCPP
}
// IntProd
List IntProd(NumericMatrix g1, NumericMatrix g2, int g1num, int g2num);
RcppExport SEXP _GGEE_IntProd(SEXP g1SEXP, SEXP g2SEXP, SEXP g1numSEXP, SEXP g2numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type g2(g2SEXP);
    Rcpp::traits::input_parameter< int >::type g1num(g1numSEXP);
    Rcpp::traits::input_parameter< int >::type g2num(g2numSEXP);
    rcpp_result_gen = Rcpp::wrap(IntProd(g1, g2, g1num, g2num));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GGEE_SVD", (DL_FUNC) &_GGEE_SVD, 1},
    {"_GGEE_cbind1", (DL_FUNC) &_GGEE_cbind1, 2},
    {"_GGEE_cbind2", (DL_FUNC) &_GGEE_cbind2, 2},
    {"_GGEE_IntProd", (DL_FUNC) &_GGEE_IntProd, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_GGEE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
