# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SVD <- function(x) {
    .Call('_GGEE_SVD', PACKAGE = 'GGEE', x)
}

cbind1 <- function(x, y) {
    .Call('_GGEE_cbind1', PACKAGE = 'GGEE', x, y)
}

cbind2 <- function(a, b) {
    .Call('_GGEE_cbind2', PACKAGE = 'GGEE', a, b)
}

IntProd <- function(g1, g2, g1num, g2num) {
    .Call('_GGEE_IntProd', PACKAGE = 'GGEE', g1, g2, g1num, g2num)
}

